name: Build
on: [push]
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Clone
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Configure
        run: cmake .
      - name: Build
        run: cmake --build . --config Debug
